### ISSUE TITLE
[ENHANCEMENT]: add a temporal save thing

### ISSUE THREAD

**Issue by Cheemsandfriends** [FunkinCrew/polymod#119]
Hello!
I was thinking of a thing that might enhance polymod in some sort of way
and that is adding temporary save options to work on.
Imagine if a mod wants to add some idk 18+ scenes (sex, slurs, whatev) but they wanna make a save for removing those stuff. they would make a parameter to their save (like flixel for example) and then they could get the save, edit it and blablabla
but if they check another mod, all the saves from the previous mod is removed so that it doesn't interfere or some shit like that?
and add like a json thing so that the modder could make a default thing like:
```json
{
        "saves": 
        {
                 "username": "MrMuffin",
                 "olderthan18": true
        }
}
```
or something like that?

**Comment by MasterEric** [comment]
I think it makes more sense for this to be done on app-by-app basis.

Users aren't necessarily running Polymod with Flixel, they may be using Heaps or NME.
